# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2fd6480898cdfeadf9939084587843d438a4aa4b484f7ce76f51b30717e63599a6390a015df381f4e3fc04bd79c72f4e48d3b3db37cac082d6bcd480e79b8912

test:
  secret_key_base: f6d812cad701beff8099f4563a30f3d6cad1f534c14328e368f155fad11a1789abae741ff23b36bed20a44cb3c64e0b35dee254dda8e99016e5086b08d6dbfc8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
